export const categoriesActions = {
  GET_CATEGORIES: "GET_CATEGORIES",
  START_FETCHING: "START_FETCHING",
  END_FETCHING: "END_FETCHING",
  ADD_SUBS: "ADD_SUBS",
  REFINE_VALUE: "REFINE_VALUE",
  SET_CURRENT_REFINEMENTS: "SET_CURRENT_REFINEMENTS",
  SET_CURRENT_STORES: "SET_CURRENT_STORES",
  REFINE_STORE: "REFINE_STORE",
  SET_MAIN_CATEGORIES: "SET_MAIN_CATEGORIES",
  SET_SEARCH_REFINEMENT: "SET_SEARCH_REFINEMENT",
  SET_IS_SEARCHING: "SET_IS_SEARCHING",
  SET_PAGINATION_DATA: "SET_PAGINATION_DATA",
  SET_HITS_PER_PAGE: "SET_HITS_PER_PAGE",
  SET_INSTANT_CHECKED: "SET_INSTANT_CHECKED",
  SET_CATALOG_CHECKED: "SET_CATALOG_CHECKED"
};

export const storesActions = {
  GET_STORES: "GET_STORES",
  START_FETCHING: "START_FETCHING",
  END_FETCHING: "END_FETCHING",
};

export const checkoutAction = {
  CHECKOUT_START_FETCHING: "CHECKOUT_START_FETCHING",
  CHECKOUT_INFO_SAVE: "CHECKOUT_INFO_SAVE",
  CHECKOUT_END_FETCHING: "CHECKOUT_END_FETCHING",
  SET_CURRENT_STEP: "SET_CURRENT_STEP",
  SET_STEP_DETAIL: "SET_STEP_DETAIL",
  SET_COURIER_STEP_DETAIL: "SET_COURIER_STEP_DETAIL",
  SET_BILLING_ADDRESS: "SET_BILLING_ADDRESS",
  GET_BILLING_ADDRESS: "GET_BILLING_ADDRESS",
  SET_ADDRESSES: "SET_ADDRESSES",
};
